### ISSUE TITLE
fix: Site RM API calls 

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#100]
Currently each monitoring point was requested for data with the following API calls to the Site-RM. 
```
POST : https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/submitdebug/NEW
GET : https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/getdebug/1650
PUT : https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/updatedebug/1650
GET : https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/getalldebughostnameactive/dummyhostname
```

@juztas Please review and provide guide on 
1. which API calls we should use
2. what typical parameter values (like run_time is currently set too small).

**Comment by juztas** [comment]
Here is a gist example: https://gist.github.com/juztas/a26ec62b6a1531097a117ad24fc14f02 (but it does ALL calls and is used for unit testing). 
For RT-Mon - use the following:
1. POST : `https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/submitdebug/NEW` - To submit a new request; If submit is successful - you will get the ID back
2. GET : `https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend/getdebug/<ID>`; Replace ID with output from received from call 1. This will get information about the status of request, something like this:
```
[{
    "id": 1651,
    "hostname": "sandie-7.ultralight.org",
    "state": "failed",
    "requestdict": "{\"hostname\": \"sandie-7.ultralight.org\", \"hosttype\": \"host\", \"type\": \"arp-push\", \"metadata\": {\"instance\": \"T2_US_Caltech_Test:sandie-7.ultralight.org\", \"flow\": \"rtmon-4beeb3a2-4093-40f9-9b0e-1954c4efe600\"}, \"gateway\": \"http://sense-mon.es.net:9091\", \"runtime\": \"1714155913\", \"resolution\": \"5\"}",
    "output": "{\"processOut\": [], \"stdout\": [], \"stderr\": [\"'output'\"], \"jsonout\": {}, \"exitCode\": 501}",
    "insertdate": 1714155305,
    "updatedate": 1714155306
}]
```
And you can check `state` key - which indicates what is the state of background process. States can be: `['new', 'active', 'failed', 'unknown']`;  new - not started yet; active - it is running; failed - failed for some reason - will not be restarted; unknown - lost information or unknown error happened;
requestdict - is what was submitted and sent to background process;
output - output information of background process. (This might be empty if unexpected error, or if process needs to run in a blocking mode, e.g. on server run iperf will wait for iperf to finish). It is currently just meant for debugging.

**Comment by xi-yang** [comment]
@sunami09 needs to change the run duration >= 3600 secs.

**Comment by sunami09** [comment]
Fixed. 
Refer to commit : d64b8eeb349cca718b41d686a9d4744b7f81e213

**Comment by xi-yang** [comment]
Let's do more tests before closing it.

**Comment by sunami09** [comment]
@sunami09 remove Update/put

**Comment by juztas** [comment]
SiteRM APIs fixed here: https://github.com/esnet/sense-rtmon/pull/116 it uses sense-o-py-client which has also siterm apis behind for easier interactions.
