### ISSUE TITLE
Split L2 Debugging Status Panels for Switch

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#108]
In the L2 Debugging Switch panel sections of the dashboard, we would like to split the status panel information to provide more information on potential failure models.

Currently:

<img width="1269" alt="single_bars" src="https://github.com/esnet/sense-rtmon/assets/30813477/27578536-2ba5-489f-b175-d9444d076408">

Due to the single status message, the message that SNMP exporter active status is a misleading one -- it is unrecoverable in terms of whether the switch is truly inactive or whether the host pointing to that switch was unable to be found in the switch's ARP / MAC table.

**Comment by PannuMuthu** [comment]
Hotfix to include multiple status panels for switches:

<img width="1272" alt="duplicate bars" src="https://github.com/esnet/sense-rtmon/assets/30813477/d7dd4c8c-7a18-4f6c-85dc-350fd8360335">


However, still need to rigorously test all scenarios:

- [ ] Correctly displays when SNMP exporter active but ARP / MAC entry unable to be found
- [ ] Does not display when SNMP exporter inactive but ARP / MAC entry able to be found (as this case should never happen in practice)
- [ ] Correctly displays when SNMP exporter inactive and ARP / MAC entry unable to be found
- [ ] Correctly displays when SNMP exporter active and ARP / MAC entry able to be found

**Comment by PannuMuthu** [comment]
We would like to test these scenarios in a clean install from the `feature-snmp-mac-debug-panels` branch which implements logic to display the failure modes for when a MAC address cannot be found. In the case where there are no MAC addresses related to the associated device, we would like to still display a failed state, rather than no display. 

#110 provides the logic to persist these metrics to Pushgateway even if the MAC addresses are not recoverable for posterity.

**Comment by PannuMuthu** [comment]
Try prototyping Script Exporter alternative via direct Prometheus query:

`sum(mac_table_info{hostname="edgecore_s0", macaddress="24:8a:07:9c:00:96", vlan="3600"}) OR on() vector(0)`

**Comment by juztas** [comment]
This is resolved in 0.01 version here: https://github.com/esnet/sense-rtmon/pull/112
