### ISSUE TITLE
Revamp / remove script_exporter

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#111]
1. L2debugging queries can be updated so that they do not depend on data from the script_exporter. The queries will be embedded into the Prometheus db side. 
2. We can potentially get rid of the script_exporter.
3. We can at least solve part of the problem that agents are generating and sending data back to the same host. (push_gw can be the other part of the problem). 
4. If we remove script_exporter, we may need to refactor the code across the code base, including the install script etc.

**Comment by juztas** [comment]
Script exported removed from autogole container deployment and it uses prometheus queries; https://github.com/esnet/sense-rtmon/pull/112

**Comment by juztas** [comment]
Closing - script exporter not used on autogole deployment.
