### ISSUE TITLE
Deploy the Site stack to Caltech and UCSD sites

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#23]
* [x] Install site stack in bare-metal / Docker mode with 1 host + 1 switch at Caltech
* [x] Verify data collection for Caltech in Cloud stack
* [x] Install site stack in k8s mode with 1 host + 1 switch at UCSD 
* [x] Verify data collection for UCSD in Cloud stack

**Comment by ZhenboYan** [comment]
Node exporter now is containerized.
- [ ] Rocky Linux
- [ ] Using no volume mapping (Github stores config and script files)
- [ ] Container working properly (tested on different machines)
- [ ] Deploy on UCSD (currently run into sandbox errors)

Next Step:
Containerize SNMP exporter 
- [ ] Rocky Linux
- [ ] No volume mapping
- [ ] Generate snmp.yml file
- [ ] Container working properly
- [ ] Deploy on UCSD
