### ISSUE TITLE
Dashboard per-flow view refinement  

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#24]
In review of the dashboard layout on dev2.virnao.com, here is a list of items to adjust.  We will add the items incrementally by development sprints. 

For `2023-q1-sprint-3` (by Feb 3):

* [x] 1. Collapse all "but" the first panel
* [x] #31
* [x] 3. Flow Summary panel groups should auto-generated "per device". If we have Switches 1, 2, 3, each of them should have its own Flow Summary Panel group that is directly mapped from the config. Also the host and switch names should be be assumed numbers like 1, 2, 3. In actual configs, they will have specific names. The panel titles should reflects those names baed on config file input.
* [x] 4. In the Host panels, the "Host Information" does not provide useful information. Some fields like interface mac address can be put in other sections. 
* [x] 5. In the Host panels, the "Packets, Bytes Receive / Transit" can be removed. Although the total counts could be useful, the graph below has mostly covers that information.
* [x] 6. After breaking up the Switch 1 & 2 into separate panel groups, rename "General Information" into "Device Information". Then "Switch 1 information" into "Port Information".  The "Interface" column can be removed as users do not care about if Index numbers.
* [x] 7. Again for each switch device, the "Packets, Bytes Receive / Transit" panels can be removed. The "Bandwidth Graph - Facing Host 1 Port" can be just "Bandwidth Graph - Facing Host 1". Make sure the name of device / host after "Facing" is autogenerated from config.
* [x] 8. All the panels in the "Flow Diagnostics" can be replaced with the Ping/ ARP panels from the other dashboard. Take a note that we may create a "TCP Performance" group to add some of these panels in the future.
* [x] 9. Change "Element Background Information" into "Host Background Load"
* [x] 10. Remove any panels in the "Miscellaneous" group that we cannot reliable get live data showing up.

Note: Everything in the panel must be autogenerated from source of truth in the config file. The generation logic should be agnostic to the number of devices in the config and agnostic to the format of naming of devices, ports etc.  

We can assume each flow has two hosts (for now). We should be able to support arbitrary number of switch devices in between. 
* [x] 11. Improve the End-to-End Flow Topology diagram  for arbitrary number of switch devices using the scheme depicted in https://github.com/esnet/sense-rtmon/issues/24#issuecomment-1403908829

**Comment by xi-yang** [comment]
```
[Host A]---[Device 1]-
                                     _-[Device 2]
                  [Device 3]-_
                                     _-[Device 4]
                            ...
                                     _-[Device 2N]
                    [Host Z]-
```

Or 

```
[Host A]---[Device 1]-
                                     _-[Device 2]
                  [Device 3]-_
                                     _-[Device 4]
                            ...
                                     _-[Device 2N]
           [Device 2N+1]-_
                                         -[Host Z]
```

**Comment by xi-yang** [comment]
@PannuMuthu I updated this JIRA ticket to DONE according the status here.
https://esnet.atlassian.net/jira/software/c/projects/SN/boards/262/roadmap?selectedIssue=SN-29

The screen shots looks great on this ticket. In the future, please add these tech details in the Github issue and only update the JIRA with brief status.   
https://esnet.atlassian.net/jira/software/c/projects/SN/boards/262/roadmap?selectedIssue=SN-30

**Comment by xi-yang** [comment]
For 11, please wrap up and check in / merge the code and then check it out.

**Comment by xi-yang** [comment]
The number of switches range from 0 to arbitrary N.

**Comment by ZhenboYan** [comment]
@sunami09 Feel free to email me with any questions you have about the project and any issues on GitHub. Read me files should be up to date but the wiki page is not yet. My email: zhenbo_yan@yahoo.com
