### ISSUE TITLE
Cloud stack SENSE-O flow metadata exchange and handling

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#28]
* [x] 1. SENSE-O API support for SENSE-RTMON flow IDSpec metadata 
* [x] 2. Create a cloud stack controller to fetch the SENSE-O metadata 
   * 2.1. SENSE-O metadata retrieval and translation into SENSE-RTMON spec 
   * 2.2. Persistent (file or DB) and in-memory data structure for processed metadata 
* [x] 3. Cloud stack workflow handling per-flow metadata 
   * [x] 3.1. Generation of flow config and dynamic dashboard 
      * Note 1: rethink the dynamic generation of queries based on this design https://github.com/sdn-sense/siterm/issues/282#issuecomment-1534926746. 
   * [x] 3.2. Generation of per-device flow data ready for dispatch to site stacks

**Comment by xi-yang** [comment]
@PannuMuthu  A solution has been applied to the SENSE-O to provide per-flow metadata via the Discovery API and Service API endpoints. Example code is under `cloud/orchestrator` folder. 

The fetch of metadata are two steps:
I. Fetch list of instance metadata with a designated SENSE-O account (say `sense-rtmon`) using a Discovery API endpoint. SENSE-O will be responsible for mark the service instances eligible for monitoring to be visible for this account.
II. Use Service API endpoint to retrieve each instance manifest using a custom template that will be filled with all the parameters required by the flow config. 


For Task 2, we need to have a controller daemon to loop through the above steps. We can use either a cached `retrieved` list or the timestamp within the instance metadata to determine which instances are new to kick off a workflow.

**Comment by xi-yang** [comment]
A SENSE-O manifest query retrieves a JSON structure like the below. Due to limitation of the manifest templating, it is not organized exactly like the SENSE-RTMON config structure. But all the information is in there. So part of Task 2.1 is to translate this into the required format. 

Also note that this example instance has only one host at one end. We want to accommodate the cases with 2, 1 and 0 hosts. How to handle the actual flow config with 0 or 1 host (like how to present them in dashboard) can be left to future tasks. 

```
{
  "Ports": [
    {
      "Port": "urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:Ethernet108",
      "Node": "sn3700_s0",
      "Peer": "?peer?",
      "Host": [
        {
          "IP Address": "10.251.86.12/24",
          "Interface": "urn:ogf:network:nrp-nautilus.io:2020:k8s-gen4-02.sdsc.optiputer.net:enp65s0np0"
        }
      ],
      "Vlan": "3911",
      "Name": "?port_name?"
    },
    {
      "Port": "urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501",
      "Node": "sn3700_s0",
      "Peer": "urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel502",
      "Vlan": "3911",
      "Name": "?port_name?"
    },
    {
      "Port": "urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel501",
      "Node": "aristaeos_s0",
      "Peer": "urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103",
      "Vlan": "3911",
      "Name": "?port_name?"
    },
    {
      "Port": "urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel502",
      "Node": "aristaeos_s0",
      "Peer": "urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501",
      "Vlan": "3911",
      "Name": "?port_name?"
    },
    {
      "Port": "urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-31",
      "Node": "dellos9_s0",
      "Peer": "?peer?",
      "Vlan": "3911",
      "Name": "?port_name?"
    },
    {
      "Port": "urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103",
      "Node": "dellos9_s0",
      "Peer": "urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel501",
      "Vlan": "3911",
      "Name": "?port_name?"
    }
  ]
}
```

**Comment by xi-yang** [comment]
Justas made the required model change to the SiteRM. The manifest template has been updated to reflect the change. The above JSON output example has also been updated. The change includes:
 * Host interface name (for NodeExporter)
 * Switch port name (for SNMPExporter)
 * Globally unique host / switch name (can be either FQDN or made up)

The above is example is complete now. Note that any field in the `?xxx?` format is a field that should be ignored.

**Comment by xi-yang** [comment]
@PannuMuthu Any update for the subtasks 2 and 3? A brief description of the design will be good.

In the meeting today, we asked to also include the service instance UUID in the breakdown per-device metadata to dispatch to the site RM.

**Comment by PannuMuthu** [comment]
Subtask 2: **Create a cloud stack controller to fetch the SENSE-O metadata** has been implemented and tested on sample SENSE-O manifests: 

**2.1. SENSE-O metadata retrieval and translation into SENSE-RTMON spec:** `orchestratorConfigConvert.py` translates SENSE-O metadata to SENSE-RTMON specific configs

**2.2. Persistent (file or DB) and in-memory data structure for processed metadata**: Modified JSON Exporter created with `configExporter.py` stores SENSE-RTMON converted configs to hosted Prometheus metrics page and monitors config modifications in order to propagate changes to SiteRM. 

Subtask 3: **Cloud stack workflow handling per-flow metadata** is in progress but requires certain modifications/additions to the SENSE-O metadata manifest. Namely, the user would specify which flow each port in the manifest belongs to in order to perform per-flow SENSE-RTMON system-specific config translation. 

Assuming this modification has been implemented in SENSE-O manifest creation, I have implemented per-flow SENSE-O --> SENSE-RTMON config translation in `orchestratorConfigConvert.py`. I tested per-flow translation of multiple flows in a single manifest on two sample testcases: `multiFlowOrdered.json` and `multiFlowUnOrdered.json`

**Comment by xi-yang** [comment]
> * **2.2. Persistent (file or DB) and in-memory data structure for processed metadata**: Modified JSON Exporter created with `configExporter.py` stores SENSE-RTMON converted configs to hosted Prometheus metrics page and monitors config modifications in order to propagate changes to SiteRM.
> 

How does `hosted Prometheus metrics page` become a data store for the converted per-flow per-site instrumentation configs? If the data has been generated, it is meant to dispatch to the site-RM. Why do we need to store it to Prometheus?
