### ISSUE TITLE
Site-RM Integration: exporters and data format porting

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#29]
The sub tasks are as follows.
* [x] 1. Set up Site RM exporters to send data to the dev2.virnao pushgateway. 
* [x] 2. Review the NodeExporter data and make changes as needed.
* [x] 3. Review the SNMPExporter data for completeness and make format changes (on Site-RM) as needed.
* [x] 4. Port ARPExporter into Site-RM and review the data
* [x] 5. Excise the dynamic dashboard generation with a `UCSD-LA_Arista-Caltech` SENSE service and review all the panels

**Comment by xi-yang** [comment]
@juztas has Caltech site-RM ready and pushes the data to dev2.virnao.com. @ZhenboYan is reviewing the data and will check for 2, 3 and 4.

**Comment by ZhenboYan** [comment]
1. [ ] Set up `dev2.virnao.` pushgateway, dashboard, script exporter.
2. [ ] Edit JSON template to accommodate `site rm` exporters. `exported_instance`, `ifDescr` to replace `ifIndex`.
3. [ ] Generate dynamic dashboards of 1 host and 1 switch and verify the data.
**duedate: 04/05/2023.

@juztas, here is what the metadata should include:
1. node exporter: {"instance": "name of the host"}. name of the host must be the same as the name under the `node` section under config_flow config files.
2. arp exporter: {"instance": "name of the host"}. Same as above.
3. snmp exporter: the ifDescr must be the same as the name under the `interface` under config_flow config files. MIB must include `ifHCInOctets` and `ifHCOutOctets`
Reference to the configuration file: https://github.com/esnet/sense-rtmon/blob/main/config_flow/multi.yml 

Is it possible to have 2 hosts running and SNMP on 2 switches? If not, at least Node exporter on 2 hosts and SNMP on 1 switch.

Next step for @ZhenboYan:
5. [ ] Generate dashboards based on an arbitrary number of switches and hosts.
6. [ ] Modify script exporter to scrape new format. No ping, change mac address scraping, SNMP scraping.
7. [ ] Modify JSON template to remove ping field.
8. [ ] Add a new table of `iperf` and `ping.`

**Comment by ZhenboYan** [comment]
L2 debugging functionalities:
1. Comparing `ip` field under host nodes with an arp-exporter on pushgateway.
2. Find the `HWaddress` from an arp-exporter and comparing with `macaddress` from the SNMP exporter.

**Comment by ZhenboYan** [comment]
Assuming configuration from the orchestrator is being populated to the configuration files correctly, this is how current structure interacts with Site RM API:

When `.generate.sh` is called, 
1. reads the configuration file and translates it to site rm API format
2. send the request to site rm to start all exporters
3. reconfigure script exporter and restart it
