### ISSUE TITLE
Site-RM Integration: cloud-to-site instrumentation API 

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#30]
On the Site-RM, it will be piggybacking to the existing SENSE RM API endpoints. Subtasks below
* [x] 1. Generate an initial draft of the API instrumentation metadata design 
   * Design document: https://docs.google.com/document/d/1LNd0OUoG-3LdeG14cBjDsaDWeC7Gf8qiZut_7uFIT-I
* [x] 2. @Justas adds the API endpoint to the Site-RM
* [x] 3. @ZhenboYan develops the initial cloud-to-site instrumentation with the following test cases
   * i. Prototype the API interactions for this design https://github.com/sdn-sense/siterm/issues/282#issuecomment-1534926746
   * ii. Think through and document what parameters are required to feed from the cloud stack workflow.
      * Note 1: we need flow ID (already available)
      * Note 2: we need site RM endpoint URL. (Xi needs to provide the site topology URI through SENSE-O manifest. Then a cloudstack config file will map that into the URL.)
* [ ] 4. Formal integration of cloud stack per-flow instrumentation workflow as described in #28 @PannuMuthu

**Comment by PannuMuthu** [comment]
High-level design diagram of SENSE-O integration with Cloud + Site Stack:

![SENSE-O  -  SENSE-RTMON Diagram](https://user-images.githubusercontent.com/30813477/228626985-c7a0d8e9-33fd-4e84-ac57-6cfffc6326bc.png)

**Comment by ZhenboYan** [comment]
Site RM API data format:

{'hostname': 'sdn-dtn-1-7.ultralight.org', 
'hosttype': 'host/switch',
'type': 'prometheus-push/arp-push', 
'metadata': {'instance': 'sdn-dtn-1-7.ultralight.org', 'flow_id': 'flow id'},
'gateway': 'dev2.virnao.com:9091', 
'runtime': 'duration in seconds',
'resolution': 'period in seconds'}

It's a dictionary in python. `type` indicates whether it's ARP or Node Exporters (SNMP if it's a switch). Inside `metadata,` that's where the tags displayed on pushgateway. `flow_id` is the unique flow that the dashboard monitors.
