### ISSUE TITLE
Refactor Dynamic Mermaid Diagram 

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#55]
The mermaid diagram generated to describe the flow states at the beginning of the dashboard does not order elements in the way described by the flow manifest. The logic of the mermaid diagram creation must be refactored to link peers based on the `peer` key in the recovered manifest.

**Comment by sunami09** [comment]
Issue Fixed: 
https://github.com/esnet/sense-rtmon/blob/28cf6fa029125ca3fc4e8fc22a2b6e8c1a157048/cloud/dynamic.py#L41
