### ISSUE TITLE
Identify + Triage Missing Script Exporter Tasks for Switches

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#56]
While preparing for the SC demo, we noticed that dashboard panels reporting Tasks 2 and 3 for switch network elements reported `no data`. Upon closer inspection, we noticed that Prometheus and Pushgateway recorded no metrics for these tasks relating to script exporter on switches.

**Comment by sunami09** [comment]
@xi-yang I will start working on this.
