### ISSUE TITLE
Containerize the main loop scripts

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#57]
The main loops and associated artifacts should be packaged into a `controller` Docker image. This will then be started as part of the docker stack. Validation of the containerization must consider:
1. autonomous run and handling of arbitrary flows that are added and removed I dynamically 
2. health monitoring and crash proof / auto restart for continuous 24/7 operations. 
3. logging with meaningful messages for operators observations / monitoring 
4. online global reconfiguration change utils (without shutdown of the service)

**Comment by sunami09** [comment]
Moved to #81
