### ISSUE TITLE
Parallelize Script Exporter Scripts within Containerized Main Loop 

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#61]
When spawning new scripts to monitor custom metrics via Script Exporter within the main loop, currently each new flow creates a customized script. Each of these scripts are run sequentially in the main loop workflow. However, this is not scalable for arbitrarily large number of flows.

In the event of multiple flows being monitored concurrently, we would like to parallelize the script exporter scripts in order to prevent workflow locks where scripts are run sequentially. This can be achieved by either:

1. **Spawning Script Exporter Scripts as Background Processes**: Instead of executing customized scripts in sequence, we can execute these scripts in parallel via background processes. Currently, the main loop experiences a number of locks throughout the workflow as each script per flow is run as a foreground process, requiring completion prior to executing the next script. Refactoring the containerized main loop workflow to execute these scripts per flow as background processes will eliminate these workflow locks.

2. **Refactoring Containerized Main Loop to Spawn Containerized Script Exporters**: Instead of customizing and executing scripts within the containerized main loop sequentially, one approach could be to modularize these elements by spawning a new Script Exporter container per flow where one container contains one customized script monitoring custom metrics for one flow.

Option **1** of executing foreground scripts as background scripts seems to be a more straightforward approach, but Option **2** seems to be best practice and more scalable in the long term. As such, the goals for this issue are as follows:

- [x] Investigate current main loop workflow and profile potential workflow locks caused by Script Exporter scripts
- [x] Implement Option **1** to execute Script Exporter scripts in the containerized main loop as background processes
- [ ] Assess improvements with respect to current load of workflow and assess whether implementing Option **2** would be valuable
- [ ] (Optional) If needed, implement Option **2** to refactor the containerized main loop workflow such that Script Exporter containers are spawned per new / modified flow configuration

**Comment by xi-yang** [comment]
Which code branch will this been developed on? I suggest a new feature branch. Also make sure to clean up the old branches.

**Comment by PannuMuthu** [comment]
Thanks for the suggestion! Both of these approaches will be implemented in separate branches titled with prefix `feature-xxx` to illustrate these changes.

**Comment by PannuMuthu** [comment]
Repository cleanup complete.
