### ISSUE TITLE
Test Scenario: Flows with non-SENSE-RM middle nodes (no monitoring)

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#69]
## Integration Test #3: Flows with non-SENSE-RM Middle Nodes

This test will examine creating flows where non-SENSE-RM middle nodes exist in the flow. This integration test was performed within the `feature-warn-for-non-sense-monitored-node` branch. To replicate this test, perform the following steps:

---

1. Clone the repository:
```
git clone https://github.com/esnet/sense-rtmon.git
```

2. Switch to the `feature-warn-for-non-sense-monitored-node` branch:
```
git checkout feature-warn-for-non-sense-monitored-node
git pull
```

3. Next, we'll confirm that we start with a clean state environment. Do this by ensuring that there are no running docker processes:
```
docker ps
```

![no-processes](https://github.com/esnet/sense-rtmon/assets/30813477/9bc0af1c-5e5d-4742-ab11-e7be242c92ce)

4. We will also want to check the SENSE orchestrator to ensure that there is a flow which is either configured as `CREATE - READY` or `REINSTATE - READY`. This flow should include either a host or switch network element which is a non-SENSE RM monitored node. For example:

![image](https://github.com/esnet/sense-rtmon/assets/30813477/20962ca1-f0bd-4b2b-a903-cb7b32adc45a)

In this example, the `RTMON-V3` flow contains a non-SENSE monitored node (i.e. the UCSD Dell SN3700 switch). The switch information is listed in the flow manifest, but we will not get any heartbeat metrics from the exporter in Pushgateway. The implemented updates in the `feature-warn-for-non-sense-monitored-node` branch will check for this case and generate dashboards warning users that the node is not able to be monitored and thus data does not exist for the node.

(Optional) If this is the first time installing SENSE-RTMON Cloud Stack on the host system, run the following script to install required dependencies.

```
./install.sh
```

5. Next, we want to execute the containerized main loop which will kick of dashboard generation and manifest monitoring every three minutes for updates to flow configs.

```
./start.sh
```

6. After running through dashboard generation, we should see the following four containers start up as a result of running the following command:
```
docker ps
```

<img width="1317" alt="Screen Shot 2024-01-25 at 8 28 25 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/882fca77-4541-4c4e-9a59-0074113d1e55">

7. In Grafana, we should now see a dashboard populated for each flow specified as `CREATE-READY` or `REINSTATE-READY` in the SENSE Orchestrator. If we navigate to the flow titled `RTMON-V3`, we should see the following panel elements in the generated dashboard:

<img width="1495" alt="Screen Shot 2024-01-25 at 8 31 10 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/b5739d57-751e-41db-a7f1-c8f52cf0e0c8">

<img width="1508" alt="Screen Shot 2024-01-25 at 8 32 03 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/7b4380fa-bb1c-4cbf-98ed-f7305c79b394">

---

**Comment by xi-yang** [comment]
The ARP panels look good. How do we verify the flow traffic graph?  Can we put two dashboard side by side and run some iperf to show their flow stats? I understand that some (most, or all) switch ports might not be able to get a VLAN level stats and thus not be able to tell the difference. But it will still be good to see the stats. We will then try finding some switch that can actually do that.

**Comment by PannuMuthu** [comment]
Repository cleanup complete.
