### ISSUE TITLE
Run Installation Script

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#71]
## Installation Script Overview

This script automates the setup process for Grafana, Prometheus, and Pushgateway, incorporating options for SSL certificate configuration. It is designed to run in a Linux environment with Docker.

### Script Content

```bash
#! /bin/bash
# START
echo "|| Grafana-Prometheus-Pushgateway Installer ||"
echo "||                                          ||"

# Read inputs and handle SSL certificate options
while getopts l: flag; do
    case "${flag}" in
    l) 
        if [ $OPTARG -gt 3 ]; then
            echo "Flag ${OPTARG} not available"
            echo "The Flags Available: "
            echo "      1) Let's Encrypt signed certificate..."
            exit 1
        fi
        input_lets=${OPTARG} ;;
    *)  echo "Illegal option" >&2; 
        exit 1;;
    esac
done

# Docker installation and login
if [ -x "$(command -v docker)" ]; then
    echo "||        Found docker..."
    docker login
else
    echo "!!    Docker command not found."
    echo "!!        Please visit https://docs.docker.com/install/ for installation instructions."
    exit 1
fi

# Additional setup steps including Docker Swarm initialization and updates
echo "!!    Starting Docker Swarm"
docker swarm init
echo "!!    downloading script exporter"
git clone https://github.com/ricoberger/script_exporter.git
dnf update -y
yum update -y
# Additional installation commands...

# SSL certificate handling based on user input
if [ -z "$input_lets" ]; then
    echo "Let's Encrypt Certificate Setup for Grafana..."
    read -r -p "Select a mode [1]: " sslmode
    sslmode=${sslmode:-1}
else
    sslmode=$input_lets
fi

# Further SSL setup and finalization steps
# ...

echo "!!    what's next?"
echo "!!    run ./start.sh to start containers"
```

**Comment by sunami09** [comment]
### Script Execution Output

Upon running the script, the following output was observed, indicating a missing Docker installation:

```plaintext
[root@ip-172-31-53-202 cloud]# ./install.sh
|| Grafana-Prometheus-Pushgateway Installer ||
||                                          ||
!!    Docker command not found.
!!        Please visit https://docs.docker.com/install/ for installation instructions.
```

This output suggests that Docker needs to be installed for the script to proceed with the setup process. Follow the [Docker installation instructions](https://docs.docker.com/install/) to prepare the environment for another script execution attempt.

**Comment by sunami09** [comment]
@xi-yang @PannuMuthu Should we include script to install docker in the `install.sh` script?

**Comment by sunami09** [comment]
# Installing Docker on RHEL

This document outlines the steps for installing Docker on a Red Hat Enterprise Linux (RHEL) system, including preinstallation requirements, the installation process, and post-installation verification.

## Preinstallation Process

Before installing Docker, certain prerequisite packages must be installed, and the Docker repository must be added to your system.

### Installing Prerequisite Packages

First, install the `yum-utils` package, which provides the `yum-config-manager` utility, among others:

```bash
sudo yum install -y yum-utils
```

**Output:**

```plaintext
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:36:12 ago on Thu 08 Feb 2024 03:37:32 AM UTC.
Package yum-utils-4.3.0-11.el9_3.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

### Adding the Docker Repository

Next, add the Docker CE repository to your system's repository list:

```bash
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
```

**Output:**

```plaintext
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
```

## Installing Docker

With the repository in place, proceed with installing Docker Engine, CLI, and containerd:

```bash
sudo yum install docker-ce docker-ce-cli containerd.io
```

During the installation, Docker's components are retrieved and installed. This process may take some time depending on your system's internet connection.

### Installation Confirmation

To confirm the installation was successful, Docker images were provided:

![Docker Installation Step 1](https://github.com/esnet/sense-rtmon/assets/66564001/7dbab51d-bc12-4482-9d5b-7e1b00ab2c46)

![Docker Installation Step 2](https://github.com/esnet/sense-rtmon/assets/66564001/2e5b1a3d-447d-4c08-9bc9-68445acec81e)

## Docker Start and Status Verification

After installing Docker, it's important to start the Docker service and verify its status to ensure it's running correctly.

### Starting Docker

```bash
sudo systemctl start docker
```

### Checking Docker's Status

To verify Docker is running as expected, use:

```bash
sudo systemctl status docker
```

This command provides the current status of the Docker service.

### Status Confirmation

The status verification step was documented with an image:

![Docker Status Verification](https://github.com/esnet/sense-rtmon/assets/66564001/b8bc9da8-4040-4d0a-9de6-3a89a0875164)

**Comment by sunami09** [comment]
# Installation Script Execution and Troubleshooting

This document details the execution of an installation script designed for setting up Grafana, Prometheus, and Pushgateway, including troubleshooting steps taken to resolve issues encountered during the process.

## Initial Script Execution

Upon running the install script, several operations were successfully completed as part of the setup process. However, an issue was encountered relating to `pip3` not being found on the system.

### Encountered Issues

The script attempted to use `pip3` for installing Python packages necessary for the installation but failed due to `pip3` not being installed:

- Attempting docker login and subsequent steps:
  
  ![Initial attempt](https://github.com/esnet/sense-rtmon/assets/66564001/00ef6a09-be2e-4514-aac5-06bf94d9faec)
  
  ![Continued setup steps](https://github.com/esnet/sense-rtmon/assets/66564001/4cd00e67-a4ba-43ed-8fd5-f11e7429625e)
  
  ![Further execution](https://github.com/esnet/sense-rtmon/assets/66564001/294779ac-3189-4965-a327-6fcd949a735b)
  
  ![Progressing through installation](https://github.com/esnet/sense-rtmon/assets/66564001/3468c453-e1a4-4c20-a372-d4dcfbc58706)
  
  ![Approaching the issue](https://github.com/esnet/sense-rtmon/assets/66564001/f2fc3678-b660-4b05-9bcb-d887d29c73a4)
  
  ![Encountering the problem](https://github.com/esnet/sense-rtmon/assets/66564001/e65e4234-0b15-4614-afc2-22313256d291)
  
  Output indicating the absence of `pip3`:

  ```plaintext
  sudo: pip3: command not found
  sudo: pip3: command not found
  ```

## Resolving the Issue

To address the absence of `pip3`, the package `python3-pip` was installed using `yum`, Red Hat's package manager:

```bash
sudo yum install python3-pip
```

This step ensured that `pip3` was available on the system, facilitating the continuation of the script execution.

- Installation confirmation:

  ![pip3 Installation](https://github.com/esnet/sense-rtmon/assets/66564001/4adcb268-d8dc-485e-baab-183ced9de073)

## Rerunning the Installation Script

With `pip3` successfully installed, the installation script was rerun. This time, the process completed without any issues, indicating a successful setup.

### Outcome

The subsequent execution of the install script worked perfectly, indicating that the earlier issue with `pip3` was successfully resolved, and all necessary components for Grafana, Prometheus, and Pushgateway were correctly installed and configured.

**Comment by sunami09** [comment]
Fixes #70

**Comment by sunami09** [comment]
@PannuMuthu should we add `sudo yum install python3-pip` in `install.sh`.

**Comment by PannuMuthu** [comment]
Nice job, great documentation! Looks like we should based on the results above. Interesting that we haven't encountered this error before though, I wonder if it is because we have previously installed it prior to building `install.sh` in the original VM. Either way, it's a good thing we are testing on a clean VM to ensure we aren't relying on any hanging installations from `dev2`.
