### ISSUE TITLE
Create a script to write update.sh

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#74]
- [x] Include 2 more fields in config.yml - path to certificates.
- [x] The script writes on the update.sh and runs the update.sh

**Comment by sunami09** [comment]
## Overview

The issue involved correctly parsing certificate paths from a YAML configuration file and using them in a bash script to automate the setup and deployment of a Docker container.

## Configuration YAML

The configuration was defined in a YAML file named `config.yml`, located in the `../config_cloud/` directory. This YAML file contained several important configurations, including paths to SSL certificates, Grafana settings, and mappings for site URLs.

### Key Configuration Elements

- **Host IP**
- **SSL Certificate Paths**
- **Grafana Configuration** (Host, Username, Password, API Token)
- **Site URL Mappings**

## Bash Script for Deployment (`update.sh`)

The script `update1.sh` was created to automate the deployment process. It includes steps to copy necessary files, build a Docker container, and perform cleanup afterward.

### Script Actions

1. **Extract Certificate Paths**: Using `grep` and `cut`, the script extracts the paths for `privatecert` and `certkey` from the `config.yml` file.

    ```bash
    PRIVATECERT_PATH=$(grep 'privatecert:' $CONFIG_YAML | cut -d ' ' -f 2 | tr -d '\n' | tr -d "'")
    CERT_PATH=$(grep 'certkey:' $CONFIG_YAML | cut -d ' ' -f 2 | tr -d '\n' | tr -d "'")
    ```

2. **Copy Necessary Files**: Copies the SSL certificates, authentication YAML, and configuration files to the current directory.

    ```bash
    cp "${PRIVATECERT_PATH}" .
    cp "${CERT_PATH}" .
    cp /root/.sense-o-auth.yaml .
    cp ../config_cloud/config.yml .
    cp -r ../config_flow .
    ```

3. **Build and Run Docker Container**: Builds a Docker container with the specified configuration and runs it in interactive mode.

    ```bash
    docker build --network host -t mainloop .
    docker run -itd mainloop
    ```

4. **Cleanup**: Removes the copied files to keep the environment clean.

    ```bash
    rm privkey.pem cert.pem .sense-o-auth.yaml config.yml
    rm -r config_flow
    ```

### Script Execution

The script is made executable and then executed to perform the deployment process.

```bash
chmod +x update1.sh
./update1.sh
```

**Comment by PannuMuthu** [comment]
Tested update of `config_cloud/config.yml` to see if updating the DNS in the config file propagates through the entire workflow:

<img width="638" alt="Screen Shot 2024-03-01 at 10 57 34 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c26cfa19-6fdc-443d-960d-3a1e37f655d1">

Updated from `dev2.virnao.com` to `dev1-host.duckdns.org` in the config file and indicated usage of this config file in `start.sh`.


Docker containers were created successfully:

<img width="1506" alt="Screen Shot 2024-03-01 at 10 56 48 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/a5130ab0-0346-4f6d-840c-cfd113e77e46">

Prometheus targets were configured successfully:

<img width="1176" alt="Screen Shot 2024-03-01 at 10 56 33 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/5cfcdf13-5233-4940-a940-e1f16dfab3de">

Grafana was succcessfully able to query the Prometheus API:

<img width="1245" alt="Screen Shot 2024-03-01 at 10 56 28 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/88ee8fcc-d951-4239-905b-c1eebe823a5d">

Containerized main loop was able to query Site-RM:

<img width="1506" alt="Screen Shot 2024-03-01 at 11 00 27 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c8b3935b-e2bc-49a5-80cf-06a969abc486">
