### ISSUE TITLE
Flows with IP on only source or destination host

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#90]
### Test Scenarios Checklist

- [x] **Create Flows with Only Source or Destination Host IP:** Ensure that flows can be created with either only the source or only the destination host IP specified.
- [x] **Run the Install Script:** Execute the installation script and verify that it completes without errors.
- [x] **Start the Containers:** Start all the necessary Docker containers as per the setup instructions and ensure they're running as expected.
- [x] **Set Up the Grafana Server:** Configure the Grafana server according to the provided documentation and ensure it's accessible.
- [x] **Verify Dashboard Creation:** Check whether the Grafana dashboard is created automatically upon setup or data ingestion.
- [x] **Terminate the Flow:** Terminate an active flow and verify that this operation completes successfully.
- [x] **Check Dashboard Deletion:** Confirm that the dashboard is appropriately deleted or updated in response to terminating the flow.
- [x] **Run Clean Script:** Execute the provided cleaning script to remove any temporary or unnecessary setup artifacts.
- [x] **Verify Container Deletion:** Ensure that the cleaning script successfully removes all related Docker containers.

**Comment by sunami09** [comment]
### Create Flows with Only Source or Destination Host IP
![image](https://github.com/esnet/sense-rtmon/assets/66564001/397603a3-0bc2-4d3b-b9f4-cf7daacedcbf)

@xi-yang tried to create a flow with the `RTMON-IT6-Caltech-SDSC` but failed.

**Comment by sunami09** [comment]
The Dashboard:

http://dev2.virnao.com:3000/d/ddihg3lz8p9fkd/a40b2a6d-21bb-5e43-8e4f-da4481d170af?orgId=1


![image](https://github.com/esnet/sense-rtmon/assets/66564001/9765a575-cef5-426e-b936-40d268a4acd2)
![image](https://github.com/esnet/sense-rtmon/assets/66564001/28234132-ffb4-4e5f-bfa6-c98545db3495)
![image](https://github.com/esnet/sense-rtmon/assets/66564001/417adc79-e97e-4c61-8f27-c8bd0628162e)

**Comment by juztas** [comment]
Close. Tested several times between ucsd/sdsc/starlight/caltech
