### ISSUE TITLE
Create an script to check the given directories are correct or not

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#98]
1. After every input we should check if directory exist or not.
2. It should abort if any directory is incorrect and should not proceed.

**Comment by sunami09** [comment]
Fixed
refer to : dbf6da9415e1ef076610ab67669e67ce53e9304a

**Comment by xi-yang** [comment]
@sunami09 you can close it if the fix has been verified for all.

**Comment by sunami09** [comment]
@xi-yang got it. Its fixed so I will close it now.
