### ISSUE TITLE
Automatically Configure Data Source via Service Account in Start Script

### ISSUE THREAD

**Issue by PannuMuthu** [esnet/sense-rtmon#99]
Updated `start.sh` and added `sa.py` to modify the logic of creating a Grafana datasource via HTTP API with a POST request after the Docker containers are spawned. `sa.py` also queries the HTTP API to create a service account and service account token to support the deprecation of API key and usage of Service Accounts in Grafana v10 (latest).

Below is a test run on dev1 host (EC2 VM):

---

Start by cleaning up the environment with `clean.sh`:
![Screen Shot 2024-04-19 at 1 40 10 PM](https://github.com/esnet/sense-rtmon/assets/30813477/9232df48-777d-47f1-96cd-8dda3e244189)

Ensure no containers are running:

![Screen Shot 2024-04-19 at 1 40 19 PM](https://github.com/esnet/sense-rtmon/assets/30813477/bf269b54-950b-4f9d-88fe-74c5175f00f0)

Review that the config file is correct:

![Screen Shot 2024-04-19 at 1 43 35 PM](https://github.com/esnet/sense-rtmon/assets/30813477/c8af2150-24e5-47d1-8084-1af210b1b598)

Run the start script via `./start.sh` which first checks for open ports and then starts up all containers:
![Screen Shot 2024-04-19 at 1 40 47 PM](https://github.com/esnet/sense-rtmon/assets/30813477/694aa542-9ad2-43d3-a1a7-ea6e90ac22f0)

Next, `sa.py` will be called to generate a service account and service account token:

![Screen Shot 2024-04-19 at 1 41 14 PM](https://github.com/esnet/sense-rtmon/assets/30813477/f267edd3-4753-4a21-b0ef-f81dfedd933b)

Next, we set up the datasource after the service account token has been successfully updated:

![Screen Shot 2024-04-19 at 1 41 21 PM](https://github.com/esnet/sense-rtmon/assets/30813477/a1167211-0021-4f2a-8be5-f4753c0d32a2)

Note that if this step fails, we will retry for a maximum of 5 times (in this case, a new datasource will not be created since we have one with the same name).

Next, we can navigate to the Grafana instance (`dev1-host.duckdns.org:3000`) to check if the service account token was successfully generated:

![Screen Shot 2024-04-19 at 1 41 34 PM](https://github.com/esnet/sense-rtmon/assets/30813477/0aa37cbf-c7be-4bc1-8d7e-c0a6d5c3bcbb)

Finally, we can check to verify that the Prometheus datasource is visible:

![Screen Shot 2024-04-19 at 1 43 57 PM](https://github.com/esnet/sense-rtmon/assets/30813477/731d6da9-cd2f-4d01-a9cd-3e0893663261)

![Screen Shot 2024-04-19 at 1 44 03 PM](https://github.com/esnet/sense-rtmon/assets/30813477/7b20c2e7-42f1-47c3-8731-7fd3889b3a30)

---

The main branch is up-to-date with the latest code changes.

**Comment by sunami09** [comment]
@xi-yang Fixed: "The data source auto config sort of works. Two things to fix (1) the retry loop should exit when a datasource connection has been successfully created (2) The URL field remains empty as seen on the portal."

see cloud/testStart.sh

**Comment by sunami09** [comment]
@xi-yang @PannuMuthu  I updated the start.sh to have the same code as testStart.sh.
So we don't have to run the testStart.sh anymore.

**Comment by sunami09** [comment]
@xi-yang I think we can close this issue.
